name: Probe matrix
on: pull_request
jobs:
  probe:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ github.event_name == 'pull_request' && fromJSON('["3.11"]') || fromJSON('["3.12"]') }}
    steps:
      - run: echo ${{ matrix.python-version }}
